---
# Two folders will be created.
# one for packer-stuff like hcl-files and you have to save your .vsphere-secrets.json
# one folder for the scripts, that you can define in the build-section
- name: Erstelle das Zielverzeichnis
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ packer_installation_directory }}"
    - "{{ packer_scripts_directory }}"

- name: Lade Packer herunter
  ansible.builtin.get_url:
    url: "{{ packer_download_url }}"
    dest: "{{ packer_installation_directory }}/packer.zip"
    mode: '0644'

- name: "Install some necessary Tools"
  ansible.builtin.yum:
    name:
      - tar-2:1.30-9.el8.x86_64
      - unzip-6.0-46.el8.x86_64
    state: present