---
- name: Konfiguriere die Firewall für Nginx
  ansible.builtin.firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ firewall_allowed_ports }}"
