---
# Render kickstart-file
- name: Render the file "{{kickstart_filename}}" and place it in "{{ nginx_web_root }}"
  ansible.builtin.template:
    src: kickstart-template.j2
    dest: "{{ nginx_web_root }}/{{kickstart_filename}}"
    mode: '0644'

